### ISSUE TITLE
too many spans

### ISSUE THREAD

**Issue by rimmesbe** [OliverGengenbach/CapstoneProjectColmarAcademy#1]
Your using span too much, those should be div's. Span is for wrapping inline text, not multiple elements, at most 1 element.

https://github.com/OliverGengenbach/CapstoneProjectColmarAcademy/blob/master/ColmarAcademyIndex.html#L20-L27

**Comment by OliverGengenbach** [comment]
ok, tried to improve. However, the text does not stay on the right side like this. what a mess.
