### ISSUE TITLE
inline flex

### ISSUE THREAD

**Issue by rimmesbe** [OliverGengenbach/CapstoneProjectColmarAcademy#4]
So what inline flex does is make the parent element (the one with this style) have inline position, and then also makes its children flex items. I don't think you want your header section inline.

https://github.com/OliverGengenbach/CapstoneProjectColmarAcademy/blob/master/resources/css/ColmarAcademyStyle.css#L16

**Comment by OliverGengenbach** [comment]
I removed that. However as you can see from the new code that I do not arrive anymore to put those links on one line and get them to the right end of the line. :-(
